#include "../Matrix.h"
#include <iostream>

DEFINE_VEC_WITH_OPS(1);
DEFINE_VEC_WITH_OPS(2);
DEFINE_VEC_WITH_OPS(3);
DEFINE_VEC_WITH_OPS(4);
DEFINE_VEC_WITH_OPS(5);
DEFINE_VEC_WITH_OPS(6);
DEFINE_VEC_WITH_OPS(7);
DEFINE_VEC_WITH_OPS(8);
DEFINE_VEC_WITH_OPS(9);

DEFINE_MAT_WITH_OPS(1);
DEFINE_MAT_WITH_OPS(2);
DEFINE_MAT_WITH_OPS(3);
DEFINE_MAT_WITH_OPS(4);
DEFINE_MAT_WITH_OPS(5);
DEFINE_MAT_WITH_OPS(6);
DEFINE_MAT_WITH_OPS(7);
DEFINE_MAT_WITH_OPS(8);
DEFINE_MAT_WITH_OPS(9);

bool testVectorOperations();
bool testMatrixOperations();